const { GoogleGenerativeAI } = require('@google/generative-ai');
const retrievalService = require('../retrieval/retrievalService');

// Initialize Gemini API client if key is available
let genAI = null;
if (process.env.GEMINI_API_KEY) {
  try {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    console.log('[AI Service] Gemini API initialized successfully.');
  } catch (error) {
    console.error('[AI Service] Failed to initialize Gemini API:', error);
  }
} else {
  console.warn('[AI Service] GEMINI_API_KEY is not defined. Falling back to Demo Mode.');
}

// System Disclaimers and Guidelines
const LEGAL_DISCLAIMER = "Disclaimer: This is an informational assessment generated by the Civic Action Engine for navigation and educational purposes. It does not constitute official legal advice or a final government eligibility determination. Please consult a qualified legal professional or the respective department officials before taking formal action.";

/**
 * Fallback Mock generator for Demo Mode
 */
const mockService = {
  routeRequest: (text) => {
    const input = text.toLowerCase();
    if (input.includes('landlord') || input.includes('rent') || input.includes('deposit') || input.includes('tenant') || input.includes('salary') || input.includes('workplace') || input.includes('employer')) {
      return {
        category: 'RIGHTS_NAVIGATOR',
        reason: 'Identified a tenant, housing, or workplace rights dispute.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('scholarship') || input.includes('scheme') || input.includes('yashasvi') || input.includes('eligible') || input.includes('pm-')) {
      return {
        category: 'SCHEME_ELIGIBILITY',
        reason: 'Inquiry relates to government schemes or scholarship eligibility criteria.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('spend') || input.includes('road') || input.includes('budget') || input.includes('rti') || input.includes('information request') || input.includes('allocated')) {
      return {
        category: 'RTI_DRAFTING',
        reason: 'Citizen wishes to seek records or files from a public authority.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('form') || input.includes('application') || input.includes('fill') || input.includes('income certificate')) {
      return {
        category: 'FORM_FILLER',
        reason: 'Citizen requests guidance completing a government application form.',
        confidence: 'HIGH'
      };
    }
    // Default fallback
    return {
      category: 'RIGHTS_NAVIGATOR',
      reason: 'Routing to General Rights Navigator for situation analysis.',
      confidence: 'MEDIUM'
    };
  },

  analyzeRights: (text) => {
    const input = text.toLowerCase();
    // Retrieve tenant source
    const sources = retrievalService.search(text, 'rights');
    
    if (input.includes('landlord') || input.includes('deposit') || input.includes('rent')) {
      return {
        summary: "Security deposit dispute with your landlord regarding unpaid return of deposits.",
        category: "Tenant Rights / Rent Disputes",
        clarificationNeeded: "1. Did you provide a formal written vacancy notice? 2. Is there a signed tenancy agreement? 3. Has the landlord provided a written list of deductions?",
        explanation: "Under the Model Tenancy Act guidelines, a landlord must return the advance security deposit within 30 days of the tenant vacating the premises. Deductions are only permitted for actual damage or unpaid dues, not for normal wear and tear.",
        nextSteps: [
          "Send a written demand notice requesting the return of the deposit within 15 days.",
          "Compile evidence including the tenancy agreement, bank transactions, and photos of the vacant room.",
          "If the landlord refuses, prepare a petition to be filed before the local Rent Authority/Tribunal."
        ],
        documentsNeeded: [
          "Tenancy Agreement",
          "Rent Receipts / Bank statement showing deposit payment",
          "Written communication (emails/messages) with landlord",
          "Vacation Notice & Proof of hand-over"
        ],
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Workplace salary mock
    return {
      summary: "Workplace dispute regarding unpaid wages/salary.",
      category: "Labor & Employment Rights",
      clarificationNeeded: "1. What was your employment designation? 2. How many months of salary remain unpaid? 3. Do you have a written appointment letter?",
      explanation: "Under the Payment of Wages Act, wages must be paid in a timely manner (usually by the 7th or 10th of the following month). If payment is withheld, workers can approach the Labour Commissioner's office.",
      nextSteps: [
        "Draft a formal request to your employer detailing the exact unpaid wages.",
        "Gather employment letters, salary slips, and attendance records.",
        "File a complaint with the regional Labour Commissioner."
      ],
      documentsNeeded: [
        "Employment Agreement / Appointment Letter",
        "Salary Slips / Bank statements",
        "Attendance records or emails showing work completed"
      ],
      sources: [],
      disclaimer: LEGAL_DISCLAIMER,
      mode: "DEMO"
    };
  },

  draftRti: (text) => {
    const sources = retrievalService.search(text, 'rti');
    
    return {
      clarificationNeeded: "What is the specific municipal ward number, PWD region, or locality name, and what years/period of construction details are you requesting?",
      subject: "Information request under Section 6(1) of the Right to Information Act, 2005 regarding local road construction and fund allocation.",
      targetAuthority: "Public Information Officer (PIO), Public Works Department (PWD) / Municipal Corporation",
      rtiDraft: `To,
The Public Information Officer,
[Office of the Public Works Department / Municipal Corporation],
[City / District Name]

Subject: Request for Information under Section 6(1) of the RTI Act, 2005.

Sir/Madam,

I, a citizen of India, hereby request the following information regarding the road construction and funds spent in my locality:

1. Please provide details of total budget allocated, sanctioned, and released for road construction, repair, and resurfacing in [SPECIFIC LOCALITY / WARD NUMBER] during the last 3 financial years.
2. Please provide a copy of the Work Order, Tender Notice, and completion certificate for work done on [SPECIFY ROAD NAME] in the past 24 months.
3. What is the name of the contractor/agency selected for this road work, and what is the specified defect liability period?
4. Please provide a copy of the measurement book entries corresponding to this construction.

Please provide the information in print format. I am enclosing the RTI Application Fee of Rs. 10/- via Postal Order/Demand Draft.

Date: ${new Date().toLocaleDateString()}
Place: [Your City]

Applicant:
Name: [Your Name]
Address: [Your Complete Address]
Phone: [Your Contact Number]`,
      instructions: [
        "Buy a Rs. 10 Court Fee Stamp or Postal Order (IPO) payable to the Accounts Officer of the public authority.",
        "Fill in your name and address in the placeholders in the draft above.",
        "Submit via Registered Post/Speed Post to the correct PIO or file online at rtionline.gov.in."
      ],
      sources: sources.length ? [sources[0]] : [],
      disclaimer: "This is a draft RTI application requiring your review and verification. Ensure all local names and addresses are filled out accurately.",
      mode: "DEMO"
    };
  }
};

/**
 * Robust JSON extraction helper for LLM responses
 */
function parseStructuredJson(text) {
  const cleaned = text.replace(/```json/g, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    const firstBrace = cleaned.indexOf('{');
    const lastBrace = cleaned.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1) {
      const braceBlock = cleaned.substring(firstBrace, lastBrace + 1);
      try {
        return JSON.parse(braceBlock);
      } catch (innerErr) {
        console.error('[AI Service] JSON brace extraction parse failed:', innerErr.message);
      }
    }
    throw e;
  }
}

/**
 * Core LLM Service
 */
const geminiService = {
  // 1. Unified intelligent router
  routeRequest: async (text) => {
    if (!genAI) {
      return mockService.routeRequest(text);
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Routing Agent of the Civic Action Engine.
        Classify the citizen's query into one of these 4 modules:
        1. 'RIGHTS_NAVIGATOR' (for landlord disputes, tenant rights, consumer complaints, workplace wages/harassment, general civic rights)
        2. 'SCHEME_ELIGIBILITY' (for government welfare schemes, scholarships, eligibility checks)
        3. 'RTI_DRAFTING' (for requesting records, budgets, files, allocations, or roads info from the government under RTI)
        4. 'FORM_FILLER' (for help filling out a specific application form, e.g. income certificate, caste certificate, birth cert)

        Input situation: "${text}"

        Provide your response as a valid JSON object matching this schema:
        {
          "category": "RIGHTS_NAVIGATOR" | "SCHEME_ELIGIBILITY" | "RTI_DRAFTING" | "FORM_FILLER",
          "reason": "short explanation of why you routed to this module",
          "confidence": "HIGH" | "MEDIUM" | "LOW"
        }
        Do not include markdown tags like \`\`\`json in the output. Just return the JSON object.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      return parseStructuredJson(responseText);
    } catch (error) {
      console.error('[Gemini Route Error] Falling back to mock routing:', error.message);
      return mockService.routeRequest(text);
    }
  },

  // 2. Rights Navigator analyzer
  analyzeRights: async (text) => {
    const sources = retrievalService.search(text, 'rights');
    const sourceText = sources.map(s => `[Source: ${s.title} (${s.authority})]\n${s.content}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.analyzeRights(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Rights Navigator module of the Civic Action Engine.
        Analyze the citizen's situation. Group your analysis based on the grounded source documents provided below.
        
        Grounded Source Material:
        ${sourceText || 'No specific official sources found. Explain general legal provisions and express uncertainty.'}

        Citizen Situation: "${text}"

        Guidelines:
        - Do not pretend to be a lawyer. Use phrasing like "Based on the available information..." or "Consider verifying...".
        - Distinguish FACT, SOURCE, INFERENCE, and RECOMMENDATION.
        - Incorporate the source authority/title in your explanations.

        Respond with a valid JSON object matching this schema:
        {
          "summary": "one sentence summary of the issue",
          "category": "e.g. Tenant Rights, Consumer Dispute, Labor Dispute",
          "clarificationNeeded": "2-3 questions to ask the user to clarify details",
          "explanation": "clear, simple language explanation of what rights apply, grounded in the source",
          "nextSteps": ["Step 1", "Step 2", "Step 3"],
          "documentsNeeded": ["Doc 1", "Doc 2"]
        }
        Do not include markdown tags in the output. Return ONLY raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);
      
      return {
        ...parsed,
        sources,
        disclaimer: LEGAL_DISCLAIMER,
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini Rights Error] Falling back to mock analysis:', error.message);
      return { ...mockService.analyzeRights(text), sources };
    }
  },

  // 3. RTI Drafting Agent
  draftRti: async (text) => {
    const sources = retrievalService.search(text, 'rti');
    const sourceText = sources.map(s => `[Source: ${s.title}]\n${s.content || ''}\nSample Qs:\n${s.sample_questions ? s.sample_questions.join('\n') : ''}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.draftRti(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the RTI Drafting Agent of the Civic Action Engine.
        Generate a structured RTI application based on the user request. Ground it on the guidelines below.

        Grounded Source Material:
        ${sourceText || 'Standard RTI Act 2005 guidelines apply.'}

        User Request: "${text}"

        Guidelines:
        - Include applicant details placeholders ([Your Name], [Your Address]).
        - Identify the likely target Public Authority (like PWD, Municipal Corp).
        - Structure clear, specific, factual questions. Do not ask for opinions.
        - Generate a formal document layout.

        Respond with a valid JSON object matching this schema:
        {
          "clarificationNeeded": "what missing info should the user provide to make the draft complete?",
          "subject": "formal subject line of the RTI",
          "targetAuthority": "suggested PIO office to send to",
          "rtiDraft": "the full text of the RTI application in a formal, copyable layout",
          "instructions": ["Step 1: pay Rs 10", "Step 2: send by speed post"]
        }
        Do not include markdown tags. Return raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);

      return {
        ...parsed,
        sources,
        disclaimer: "This is a draft RTI application generated under the RTI Act, 2005. It requires your review and verification prior to filing.",
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini RTI Error] Falling back to mock draft:', error.message);
      return { ...mockService.draftRti(text), sources };
    }
  }
};

module.exports = geminiService;
