const { GoogleGenerativeAI } = require('@google/generative-ai');
const retrievalService = require('../retrieval/retrievalService');

// Initialize Gemini API client if key is available
let genAI = null;
if (process.env.GEMINI_API_KEY) {
  try {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    console.log('[AI Service] Gemini API initialized successfully.');
  } catch (error) {
    console.error('[AI Service] Failed to initialize Gemini API:', error);
  }
} else {
  console.warn('[AI Service] GEMINI_API_KEY is not defined. Falling back to Demo Mode.');
}

// System Disclaimers and Guidelines
const LEGAL_DISCLAIMER = "Disclaimer: This is an informational assessment generated by the Civic Action Engine for navigation and educational purposes. It does not constitute official legal advice or a final government eligibility determination. Please consult a qualified legal professional or the respective department officials before taking formal action.";

/**
 * Fallback Mock generator for Demo Mode
 */
const mockService = {
  routeRequest: (text) => {
    const input = text.toLowerCase();
    if (input.includes('landlord') || input.includes('rent') || input.includes('deposit') || input.includes('tenant') || input.includes('salary') || input.includes('workplace') || input.includes('employer')) {
      return {
        category: 'RIGHTS_NAVIGATOR',
        reason: 'Identified a tenant, housing, or workplace rights dispute.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('scholarship') || input.includes('scheme') || input.includes('yashasvi') || input.includes('eligible') || input.includes('pm-')) {
      return {
        category: 'SCHEME_ELIGIBILITY',
        reason: 'Inquiry relates to government schemes or scholarship eligibility criteria.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('spend') || input.includes('road') || input.includes('budget') || input.includes('rti') || input.includes('information request') || input.includes('allocated')) {
      return {
        category: 'RTI_DRAFTING',
        reason: 'Citizen wishes to seek records or files from a public authority.',
        confidence: 'HIGH'
      };
    }
    if (input.includes('form') || input.includes('application') || input.includes('fill') || input.includes('income certificate')) {
      return {
        category: 'FORM_FILLER',
        reason: 'Citizen requests guidance completing a government application form.',
        confidence: 'HIGH'
      };
    }
    // Default fallback
    return {
      category: 'RIGHTS_NAVIGATOR',
      reason: 'Routing to General Rights Navigator for situation analysis.',
      confidence: 'MEDIUM'
    };
  },

  analyzeRights: (text) => {
    const input = text.toLowerCase();
    const sources = retrievalService.search(text, 'rights');
    
    // Landlord dispute mock
    if (input.includes('landlord') || input.includes('deposit') || input.includes('rent')) {
      return {
        whatWeUnderstand: "You vacated your rented room, but the landlord is withholding the refund of your advance security deposit without valid justification.",
        informationThatMayApply: "Under Chapter IV of the Model Tenancy Act guidelines, advance security deposits for residential properties are capped at a maximum of two months' rent. The landlord is legally required to refund the deposit upon taking over vacant possession.",
        why: "A landlord may make deductions only for outstanding utility bills, unpaid rent, or actual tenant-caused damage. Deductions for normal wear and tear (like standard paint weathering) are not permitted. If deductions are made without a written itemized list or if the refund is withheld beyond 30 days, the tenant can approach the local Rent Tribunal.",
        whatYouMayDoNext: [
          "Send a written demand notice requesting the return of the deposit within 15 days.",
          "Compile receipts showing deposit payments, tenancy agreements, and pictures of the vacant room.",
          "File a formal dispute petition before the Rent Authority or Rent Tribunal."
        ],
        documentsEvidenceThatMayHelp: [
          "Tenancy Agreement",
          "Rent Receipts / Bank statement showing deposit payment",
          "Written communication (emails/messages) with landlord",
          "Vacation Notice & Proof of hand-over"
        ],
        importantLimitations: "This is a general guide. Tenancy laws vary by state jurisdictions. If your agreement was not registered, local civil courts or mediation centers may apply instead of the specialized Rent Authority.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Workplace Salary Mock
    return {
      whatWeUnderstand: "Your wages/salary remain unpaid or delayed by your employer, violating timely payment standards.",
      informationThatMayApply: "Under the Payment of Wages Act, 1936, employers are obligated to pay all wages in cash, cheque, or bank transfer in a timely manner (by the 7th of the following month for establishments with < 1000 workers).",
      why: "Section 7 strictly limits authorized deductions. Withholding salary due to arbitrary disputes is illegal. Workers are entitled to receive full wages along with compensation for delayed payments by submitting claims to the regional labour department.",
      whatYouMayDoNext: [
        "Send a written salary demand letter to your employer via registered post/email.",
        "Gather employment details, appointment letters, salary slips, and attendance sheets.",
        "Submit a formal complaint claim under Section 15 of the Act to the Labour Commissioner."
      ],
      documentsEvidenceThatMayHelp: [
        "Employment Agreement / Appointment Letter",
        "Salary Slips / Bank statements",
        "Attendance records or emails showing work completed"
      ],
      importantLimitations: "This Act primarily covers employees drawing salary below specified statutory thresholds. Higher-earning executives may need to seek recovery via standard civil suit litigation or arbitration panels.",
      sources: sources.length ? [sources[0]] : [],
      disclaimer: LEGAL_DISCLAIMER,
      mode: "DEMO"
    };
  },

  draftRti: (text) => {
    const sources = retrievalService.search(text, 'rti');
    
    return {
      clarificationNeeded: "What is the specific municipal ward number, PWD region, or locality name, and what years/period of construction details are you requesting?",
      subject: "Information request under Section 6(1) of the Right to Information Act, 2005 regarding local road construction and fund allocation.",
      targetAuthority: "[Needs your input: Target PIO Office (e.g. Executive Engineer, PWD / Ward Assistant Commissioner)]",
      rtiDraft: `To,
The Public Information Officer,
[Needs your input: Public Authority Department Office Name],
[Needs your input: City / District / State]

Subject: Request for Information under Section 6(1) of the RTI Act, 2005.

Sir/Madam,

I, a citizen of India, hereby request the following information regarding the road construction and funds spent in my locality:

1. Please provide details of total budget allocated, sanctioned, and released for road construction, repair, and resurfacing in [Needs your input: Locality Name / Ward Number] during the last 3 financial years.
2. Please provide a copy of the Work Order, Tender Notice, and completion certificate for work done on [Needs your input: Specific Road Name] in the past 24 months.
3. What is the name of the contractor/agency selected for this road work, and what is the specified defect liability period?
4. Please provide a copy of the measurement book entries corresponding to this construction.

Please provide the information in print format. I am enclosing the RTI Application Fee of Rs. 10/- via Postal Order/Demand Draft.

Date: ${new Date().toLocaleDateString()}
Place: [Needs your input: Your City]

Applicant:
Name: [Needs your input: Applicant Name]
Address: [Needs your input: Applicant Complete Address]
Phone: [Needs your input: Applicant Contact Number]`,
      instructions: [
        "Buy a Rs. 10 Court Fee Stamp or Postal Order (IPO) payable to the Accounts Officer of the public authority.",
        "Fill in your name and address in the placeholders in the draft above.",
        "Submit via Registered Post/Speed Post to the correct PIO or file online at rtionline.gov.in."
      ],
      sources: sources.length ? [sources[0]] : [],
      disclaimer: "This is a draft RTI application requiring your review and verification. Ensure all local names and addresses are filled out accurately.",
      mode: "DEMO"
    };
  }
};

/**
 * Robust JSON extraction helper for LLM responses
 */
function parseStructuredJson(text) {
  const cleaned = text.replace(/```json/g, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    const firstBrace = cleaned.indexOf('{');
    const lastBrace = cleaned.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1) {
      const braceBlock = cleaned.substring(firstBrace, lastBrace + 1);
      try {
        return JSON.parse(braceBlock);
      } catch (innerErr) {
        console.error('[AI Service] JSON brace extraction parse failed:', innerErr.message);
      }
    }
    throw e;
  }
}

/**
 * Core LLM Service
 */
const geminiService = {
  // 1. Unified intelligent router
  routeRequest: async (text) => {
    if (!genAI) {
      return mockService.routeRequest(text);
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Routing Agent of the Civic Action Engine.
        Classify the citizen's query into one of these 4 modules:
        1. 'RIGHTS_NAVIGATOR' (for landlord disputes, tenant rights, consumer complaints, workplace wages/harassment, general civic rights)
        2. 'SCHEME_ELIGIBILITY' (for government welfare schemes, scholarships, eligibility checks)
        3. 'RTI_DRAFTING' (for requesting records, budgets, files, allocations, or roads info from the government under RTI)
        4. 'FORM_FILLER' (for help filling out a specific application form, e.g. income certificate, caste certificate, birth cert)

        Input situation: "${text}"

        Provide your response as a valid JSON object matching this schema:
        {
          "category": "RIGHTS_NAVIGATOR" | "SCHEME_ELIGIBILITY" | "RTI_DRAFTING" | "FORM_FILLER",
          "reason": "short explanation of why you routed to this module",
          "confidence": "HIGH" | "MEDIUM" | "LOW"
        }
        Do not include markdown tags like \`\`\`json in the output. Just return the JSON object.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      return parseStructuredJson(responseText);
    } catch (error) {
      console.error('[Gemini Route Error] Falling back to mock routing:', error.message);
      return mockService.routeRequest(text);
    }
  },

  // 2. Rights Navigator analyzer
  analyzeRights: async (text) => {
    const sources = retrievalService.search(text, 'rights');
    const sourceText = sources.map(s => `[Source: ${s.title} (${s.authority})]\n${s.content}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.analyzeRights(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Rights Navigator module of the Civic Action Engine.
        Analyze the citizen's situation. Group your analysis based on the grounded source documents provided below.
        
        Grounded Source Material:
        ${sourceText || 'No specific official sources found. Explain general legal provisions and express uncertainty.'}

        Citizen Situation: "${text}"

        Guidelines:
        - Do not pretend to be a lawyer. Use phrasing like "Based on the available information..." or "Consider verifying...".
        - Distinguish FACT, SOURCE, INFERENCE, and RECOMMENDATION.
        - Incorporate the source authority/title in your explanations.
        - Ensure all key outputs fit the required sections in simple language.

        Respond with a valid JSON object matching this schema:
        {
          "whatWeUnderstand": "one sentence summarizing what we understand about the dispute facts",
          "informationThatMayApply": "simple explanation of what rights or rules may apply to this situation",
          "why": "detailed reasoning of why they apply or why they are violated, citing source documents",
          "whatYouMayDoNext": ["Step 1 description", "Step 2 description", "Step 3 description"],
          "documentsEvidenceThatMayHelp": ["Evidence Document 1", "Evidence Document 2"],
          "importantLimitations": "clear limitations, state variations, jurisdictional details, and general uncertainties"
        }
        Do not include markdown tags in the output. Return ONLY raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);
      
      return {
        ...parsed,
        sources,
        disclaimer: LEGAL_DISCLAIMER,
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini Rights Error] Falling back to mock analysis:', error.message);
      return { ...mockService.analyzeRights(text), sources };
    }
  },

  // 3. RTI Drafting Agent
  draftRti: async (text) => {
    const sources = retrievalService.search(text, 'rti');
    const sourceText = sources.map(s => `[Source: ${s.title}]\n${s.content || ''}\nSample Qs:\n${s.sample_questions ? s.sample_questions.join('\n') : ''}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.draftRti(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the RTI Drafting Agent of the Civic Action Engine.
        Generate a structured RTI application based on the user request. Ground it on the guidelines below.

        Grounded Source Material:
        ${sourceText || 'Standard RTI Act 2005 guidelines apply.'}

        User Request: "${text}"

        Guidelines:
        - If the applicant name or address is not supplied, use placeholders matching "[Needs your input: Applicant Name]" and "[Needs your input: Applicant Complete Address]". Do not guess or invent them!
        - If the department name or city is not supplied, use placeholders matching "[Needs your input: Public Authority Department Office Name]" and "[Needs your input: City/District]".
        - Structure clear, specific, factual questions. Do not ask for opinions.
        - Generate a formal document layout.

        Respond with a valid JSON object matching this schema:
        {
          "clarificationNeeded": "what missing details should the user supply to make the draft complete?",
          "subject": "formal subject line of the RTI",
          "targetAuthority": "suggested PIO office or department name",
          "rtiDraft": "the full text of the RTI application in a formal, copyable layout",
          "instructions": ["Step 1: pay Rs 10", "Step 2: send by speed post"]
        }
        Do not include markdown tags. Return raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);

      return {
        ...parsed,
        sources,
        disclaimer: "This is a draft RTI application generated under the RTI Act, 2005. It requires your review and verification prior to filing.",
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini RTI Error] Falling back to mock draft:', error.message);
      return { ...mockService.draftRti(text), sources };
    }
  }
};

module.exports = geminiService;
