const { GoogleGenerativeAI } = require('@google/generative-ai');
const retrievalService = require('../retrieval/retrievalService');

// Initialize Gemini API client if key is available
let genAI = null;
if (process.env.GEMINI_API_KEY) {
  try {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    console.log('[AI Service] Gemini API initialized successfully.');
  } catch (error) {
    console.error('[AI Service] Failed to initialize Gemini API:', error);
  }
} else {
  console.warn('[AI Service] GEMINI_API_KEY is not defined. Falling back to Demo Mode.');
}

// System Disclaimers and Guidelines
const LEGAL_DISCLAIMER = "Disclaimer: This is an informational assessment generated by the Civic Action Engine for navigation and educational purposes. It does not constitute official legal advice or a final government eligibility determination. Please consult a qualified legal professional or the respective department officials before taking formal action.";

/**
 * Fallback Mock generator for Demo Mode
 */
const mockService = {
  routeRequest: (text) => {
    const input = text.toLowerCase().trim();
    
    let category = "Other Civic Issue";
    let module = "RIGHTS_NAVIGATOR";
    let confidence = "LOW";
    let needsClarification = false;
    let reason = "Classifying using taxonomy keywords.";

    if (!input) {
      return {
        category: "Other Civic Issue",
        module: "RIGHTS_NAVIGATOR",
        confidence: "LOW",
        needsClarification: false,
        reason: "Empty input query."
      };
    }

    if (input.includes('landlord') || input.includes('rent') || input.includes('deposit') || input.includes('tenant')) {
      category = "Housing / Tenant";
      module = "RIGHTS_NAVIGATOR";
      confidence = "HIGH";
    } else if (input.includes('employer') || input.includes('salary') || input.includes('wages') || input.includes('pay') || input.includes('job') || input.includes('workplace') || input.includes('wage')) {
      category = "Employment / Wage";
      module = "RIGHTS_NAVIGATOR";
      confidence = "HIGH";
      if (input === 'my employer is treating me unfairly' || input === 'workplace dispute' || input.includes('unfairly')) {
        needsClarification = true;
        confidence = "MEDIUM";
      }
    } else if (input.includes('refund') || input.includes('product') || input.includes('seller') || input.includes('buy') || input.includes('shop') || input.includes('store') || input.includes('consumer') || input.includes('phone')) {
      category = "Consumer / Refund";
      module = "RIGHTS_NAVIGATOR";
      confidence = "HIGH";
    } else if (input.includes('police') || input.includes('brutality') || input.includes('force') || input.includes('arrest') || input.includes('detained') || input.includes('cop') || input.includes('stopped')) {
      category = "Police / Public Authority";
      module = "RIGHTS_NAVIGATOR";
      confidence = "MEDIUM";
      needsClarification = true;
    } else if (input.includes('garbage') || input.includes('waste') || input.includes('sanitation') || input.includes('rubbish') || input.includes('cleaning')) {
      category = "Sanitation / Waste";
      module = "RIGHTS_NAVIGATOR";
      confidence = "HIGH";
    } else if (input.includes('road') || input.includes('pothole') || input.includes('infrastructure') || input.includes('street') || input.includes('pavement')) {
      category = "Roads / Public Infrastructure";
      confidence = "HIGH";
      if (input.includes('spend') || input.includes('budget') || input.includes('allocated') || input.includes('spent') || input.includes('rti') || input.includes('spent on road')) {
        module = "RTI_DRAFTING";
      } else {
        module = "RIGHTS_NAVIGATOR";
      }
    } else if (input.includes('scholarship') || input.includes('yashasvi') || input.includes('scheme') || input.includes('qualify')) {
      category = "Education";
      module = "SCHEME_ELIGIBILITY";
      confidence = "HIGH";
    } else if (input.includes('fill') || input.includes('application') || input.includes('income certificate') || input.includes('form')) {
      category = "Identity / Public Documents";
      module = "FORM_FILLER";
      confidence = "HIGH";
    } else if (input.includes('patent') || input.includes('trading') || input.includes('stock') || input.includes('cook') || input.includes('code') || input.includes('unrelated') || input.includes('cooking')) {
      category = "Other Civic Issue";
      module = "RIGHTS_NAVIGATOR";
      confidence = "LOW";
      reason = "This request is outside the scope of our supported legal/civic knowledge base.";
    }

    return { category, module, confidence, needsClarification, reason };
  },

  analyzeRights: (text) => {
    const input = text.toLowerCase();
    const sources = retrievalService.search(text, 'rights');
    
    // Landlord dispute mock
    if (input.includes('landlord') || input.includes('deposit') || input.includes('rent')) {
      return {
        whatWeUnderstand: "You vacated your rented room, but the landlord is withholding the refund of your advance security deposit without valid justification.",
        informationThatMayApply: "Under Chapter IV of the Model Tenancy Act guidelines, advance security deposits for residential properties are capped at a maximum of two months' rent. The landlord is legally required to refund the deposit upon taking over vacant possession.",
        why: "A landlord may make deductions only for outstanding utility bills, unpaid rent, or actual tenant-caused damage. Deductions for normal wear and tear (like standard paint weathering) are not permitted. If deductions are made without a written itemized list or if the refund is withheld beyond 30 days, the tenant can approach the local Rent Tribunal.",
        whatYouMayDoNext: [
          "Send a written demand notice requesting the return of the deposit within 15 days.",
          "Compile receipts showing deposit payments, tenancy agreements, and pictures of the vacant room.",
          "File a formal dispute petition before the Rent Authority or Rent Tribunal."
        ],
        documentsEvidenceThatMayHelp: [
          "Tenancy Agreement",
          "Rent Receipts / Bank statement showing deposit payment",
          "Written communication (emails/messages) with landlord",
          "Vacation Notice & Proof of hand-over"
        ],
        importantLimitations: "This is a general guide. Tenancy laws vary by state jurisdictions. If your agreement was not registered, local civil courts or mediation centers may apply instead of the specialized Rent Authority.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Police Complaint Mock
    if (input.includes('police') || input.includes('brutality') || input.includes('force') || input.includes('arrest') || input.includes('detained') || input.includes('cop') || input.includes('stopped') || input.includes('threatened')) {
      return {
        whatWeUnderstand: "You are reporting police misconduct, which may include the use of excessive physical force, threat/intimidation, or illegal detention.",
        informationThatMayApply: "Under Supreme Court guidelines on police reforms and respective state Police Acts, citizens are protected against police abuse of authority. Independent Police Complaints Authorities (PCA) are mandated at the state and district levels to investigate serious misconduct.",
        why: "A complaint can be filed before the PCA for grievances like custodial excess, grievous hurt, extortion, or abuse of power. CPGRAMS and departmental vigilance units also accept grievances. The complaint must contain specific officer details and supporting medical or media records.",
        whatYouMayDoNext: [
          "Record all incident details immediately, including date, time, officer names, belt numbers, and witness contacts.",
          "Seek medical attention immediately and secure a Medico-Legal Case (MLC) report if physical force was used.",
          "File a written complaint with the Police Complaints Authority (PCA) or submit a grievance on CPGRAMS."
        ],
        documentsEvidenceThatMayHelp: [
          "Medico-Legal Case (MLC) Report / Hospital records",
          "Photographs or video/audio recordings of the incident",
          "Eyewitness statements",
          "Copy of any arbitrary fine slips or seizure memos"
        ],
        importantLimitations: "The PCA operates as a disciplinary audit authority. It can recommend suspensions or departmental actions but cannot directly award financial damages or cancel formal criminal charges (FIRs), which requires petitioning the High Court.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Sanitation & Waste Mock
    if (input.includes('garbage') || input.includes('waste') || input.includes('sanitation') || input.includes('rubbish')) {
      return {
        whatWeUnderstand: "You are reporting neglected municipal garbage collection or open waste dumping in your locality.",
        informationThatMayApply: "Under the Solid Waste Management Rules, 2016, municipal authorities have a statutory duty to collect segregated waste daily, clear public street bins, and maintain clean public areas.",
        why: "Solid Waste Management Rules, 2016 legally obligate urban local bodies to organize waste transport and disposal. If local collectors fail to clear rubbish, citizens can file digital complaints on the national Swachhata app or escalate to the Ward Sanitary Inspector.",
        whatYouMayDoNext: [
          "Take geotagged photos of the accumulated garbage or open dump.",
          "Submit a digital complaint ticket on the Swachhata App or the municipal e-district portal.",
          "Coordinate with the local Resident Welfare Association (RWA) to file a group petition with the Ward Health Inspector."
        ],
        documentsEvidenceThatMayHelp: [
          "Photographs of waste accumulation with timestamp",
          "Reference numbers of previous unanswered complaint tickets",
          "Resident petition letters signed by neighbors"
        ],
        importantLimitations: "Municipal response times can vary depending on local budget allocations and outsourced contractor worker availability. Severe structural issues may require higher municipal health commissioner escalations.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Roads & Infrastructure Mock
    if (input.includes('road') || input.includes('pothole') || input.includes('infrastructure') || input.includes('street') || input.includes('pavement')) {
      return {
        whatWeUnderstand: "You are reporting damaged roads, broken street pavements, or potholes causing safety hazards.",
        informationThatMayApply: "Under PWD road manuals and municipal Citizens' Charters, local public works divisions are responsible for street safety and timely pothole repairs.",
        why: "Municipalities and PWD are legally responsible for road maintenance. The citizens' charter states that reported pothole defects must be repaired within 48 to 72 hours. Photo grievances filed on municipal apps or written letters to the Executive Engineer are the primary action routes.",
        whatYouMayDoNext: [
          "Capture photos of the damaged road sections, highlighting the safety hazard to vehicles/pedestrians.",
          "Register a grievance ticket on the local municipal corporation app or portal.",
          "Draft and deliver a formal complaint notice to the Public Works Department (PWD) Executive Engineer."
        ],
        documentsEvidenceThatMayHelp: [
          "Geotagged photos of potholes or broken pavements",
          "Doctor's report/bill if the road defect caused a vehicle accident or injury",
          "Standard written complaint draft with location coordinates"
        ],
        importantLimitations: "Arterial roads and neighborhood colony lanes fall under different jurisdictions (State PWD vs. Local Municipal Corporation). Sending the complaint to the wrong body can delay repairs.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Consumer Refund Mock
    if (input.includes('refund') || input.includes('defective') || input.includes('seller') || input.includes('product') || input.includes('consumer') || input.includes('phone') || input.includes('phone online')) {
      return {
        whatWeUnderstand: "You purchased a product (like a phone) online, and the seller is refusing to issue a refund or replacement for a defective item.",
        informationThatMayApply: "Under the Consumer Protection Act, 2019, citizens are protected against unfair trade practices and receiving defective goods. E-commerce platforms are mandated to resolve consumer grievances.",
        why: "Section 2(47) defines refusing to take back defective goods or refund money within 30 days as an unfair trade practice. Consumers are entitled to seek relief by registering complaints on the National Consumer Helpline or filing petitions before the Consumer Commission.",
        whatYouMayDoNext: [
          "Call the National Consumer Helpline at 1915 or register an online complaint on the INGRAM portal.",
          "Send a formal written notice to the e-commerce company's grievance officer demanding a refund within 7 days.",
          "If unresolved, file an e-daakhil case before the District Consumer Disputes Redressal Commission."
        ],
        documentsEvidenceThatMayHelp: [
          "Invoice / Purchase receipt",
          "Photos/Video of the defective product",
          "Chat logs, emails, or call records with customer support",
          "Copy of the return policy terms"
        ],
        importantLimitations: "The Consumer Protection Act applies only if you bought the product for personal use. Commercial purchases are excluded and fall under general contract litigation.",
        sources: sources.length ? [sources[0]] : [],
        disclaimer: LEGAL_DISCLAIMER,
        mode: "DEMO"
      };
    }

    // Workplace Salary Mock (default fallback)
    return {
      whatWeUnderstand: "Your wages/salary remain unpaid or delayed by your employer, violating timely payment standards.",
      informationThatMayApply: "Under the Payment of Wages Act, 1936, employers are obligated to pay all wages in cash, cheque, or bank transfer in a timely manner (by the 7th of the following month for establishments with < 1000 workers).",
      why: "Section 7 strictly limits authorized deductions. Withholding salary due to arbitrary disputes is illegal. Workers are entitled to receive full wages along with compensation for delayed payments by submitting claims to the regional labour department.",
      whatYouMayDoNext: [
        "Send a written salary demand letter to your employer via registered post/email.",
        "Gather employment details, appointment letters, salary slips, and attendance sheets.",
        "Submit a formal complaint claim under Section 15 of the Act to the Labour Commissioner."
      ],
      documentsEvidenceThatMayHelp: [
        "Employment Agreement / Appointment Letter",
        "Salary Slips / Bank statements",
        "Attendance records or emails showing work completed"
      ],
      importantLimitations: "This Act primarily covers employees drawing salary below specified statutory thresholds. Higher-earning executives may need to seek recovery via standard civil suit litigation or arbitration panels.",
      sources: sources.length ? [sources[0]] : [],
      disclaimer: LEGAL_DISCLAIMER,
      mode: "DEMO"
    };
  },

  draftRti: (text) => {
    const sources = retrievalService.search(text, 'rti');
    
    return {
      clarificationNeeded: "What is the specific municipal ward number, PWD region, or locality name, and what years/period of construction details are you requesting?",
      subject: "Information request under Section 6(1) of the Right to Information Act, 2005 regarding local road construction and fund allocation.",
      targetAuthority: "[Needs your input: Target PIO Office (e.g. Executive Engineer, PWD / Ward Assistant Commissioner)]",
      rtiDraft: `To,
The Public Information Officer,
[Needs your input: Public Authority Department Office Name],
[Needs your input: City / District / State]

Subject: Request for Information under Section 6(1) of the RTI Act, 2005.

Sir/Madam,

I, a citizen of India, hereby request the following information regarding the road construction and funds spent in my locality:

1. Please provide details of total budget allocated, sanctioned, and released for road construction, repair, and resurfacing in [Needs your input: Locality Name / Ward Number] during the last 3 financial years.
2. Please provide a copy of the Work Order, Tender Notice, and completion certificate for work done on [Needs your input: Specific Road Name] in the past 24 months.
3. What is the name of the contractor/agency selected for this road work, and what is the specified defect liability period?
4. Please provide a copy of the measurement book entries corresponding to this construction.

Please provide the information in print format. I am enclosing the RTI Application Fee of Rs. 10/- via Postal Order/Demand Draft.

Date: ${new Date().toLocaleDateString()}
Place: [Needs your input: Your City]

Applicant:
Name: [Needs your input: Applicant Name]
Address: [Needs your input: Applicant Complete Address]
Phone: [Needs your input: Applicant Contact Number]`,
      instructions: [
        "Buy a Rs. 10 Court Fee Stamp or Postal Order (IPO) payable to the Accounts Officer of the public authority.",
        "Fill in your name and address in the placeholders in the draft above.",
        "Submit via Registered Post/Speed Post to the correct PIO or file online at rtionline.gov.in."
      ],
      sources: sources.length ? [sources[0]] : [],
      disclaimer: "This is a draft RTI application requiring your review and verification. Ensure all local names and addresses are filled out accurately.",
      mode: "DEMO"
    };
  }
};

/**
 * Robust JSON extraction helper for LLM responses
 */
function parseStructuredJson(text) {
  const cleaned = text.replace(/```json/g, '').replace(/```/g, '').trim();
  try {
    return JSON.parse(cleaned);
  } catch (e) {
    const firstBrace = cleaned.indexOf('{');
    const lastBrace = cleaned.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace !== -1) {
      const braceBlock = cleaned.substring(firstBrace, lastBrace + 1);
      try {
        return JSON.parse(braceBlock);
      } catch (innerErr) {
        console.error('[AI Service] JSON brace extraction parse failed:', innerErr.message);
      }
    }
    throw e;
  }
}

/**
 * Core LLM Service
 */
const geminiService = {
  // 1. Unified intelligent router
  routeRequest: async (text) => {
    if (!genAI) {
      return mockService.routeRequest(text);
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Routing Agent of the Civic Action Engine.
        Classify the citizen's query into one of these 4 modules:
        - 'RIGHTS_NAVIGATOR' (for tenant disputes, wages, refund complaints, police misconduct, local sanitation, public road repairs)
        - 'SCHEME_ELIGIBILITY' (for government welfare schemes, scholarships, eligibility checks)
        - 'RTI_DRAFTING' (for requesting government files, road budgets, or information records under the RTI Act)
        - 'FORM_FILLER' (for completing application forms, e.g. income certificate)

        Also identify the specific taxonomy category of the query out of these 15 options:
        - "Housing / Tenant"
        - "Employment / Wage"
        - "Consumer / Refund"
        - "Police / Public Authority"
        - "Education"
        - "Healthcare / Public Health"
        - "Accessibility / Disability"
        - "Public Utilities"
        - "Sanitation / Waste"
        - "Roads / Public Infrastructure"
        - "Local Government Services"
        - "Identity / Public Documents"
        - "Public Safety"
        - "Environmental / Pollution"
        - "Other Civic Issue"

        Assess if the query is vague/ambiguous and needs further clarification questions (set needsClarification = true).
        Assess the routing confidence (HIGH if it clearly matches supported categories, MEDIUM if it needs clarification, LOW if it is completely unsupported/out-of-scope).

        Input situation: "${text}"

        Provide your response as a valid JSON object matching this schema:
        {
          "category": "One of the 15 taxonomy category strings exactly",
          "module": "RIGHTS_NAVIGATOR" | "SCHEME_ELIGIBILITY" | "RTI_DRAFTING" | "FORM_FILLER",
          "confidence": "HIGH" | "MEDIUM" | "LOW",
          "needsClarification": true | false,
          "reason": "short explanation of your decision"
        }
        Do not include markdown tags like \`\`\`json. Return ONLY raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      return parseStructuredJson(responseText);
    } catch (error) {
      console.error('[Gemini Route Error] Falling back to mock routing:', error.message);
      return mockService.routeRequest(text);
    }
  },

  // 2. Rights Navigator analyzer
  analyzeRights: async (text) => {
    const sources = retrievalService.search(text, 'rights');
    const sourceText = sources.map(s => `[Source: ${s.title} (${s.authority})]\n${s.content}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.analyzeRights(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the Rights Navigator module of the Civic Action Engine.
        Analyze the citizen's situation. Group your analysis based on the grounded source documents provided below.
        
        Grounded Source Material:
        ${sourceText || 'No specific official sources found. Explain general legal provisions and express uncertainty.'}

        Citizen Situation: "${text}"

        Guidelines:
        - Do not pretend to be a lawyer. Use phrasing like "Based on the available information..." or "Consider verifying...".
        - Distinguish FACT, SOURCE, INFERENCE, and RECOMMENDATION.
        - Incorporate the source authority/title in your explanations.
        - Ensure all key outputs fit the required sections in simple language.

        Respond with a valid JSON object matching this schema:
        {
          "whatWeUnderstand": "one sentence summarizing what we understand about the dispute facts",
          "informationThatMayApply": "simple explanation of what rights or rules may apply to this situation",
          "why": "detailed reasoning of why they apply or why they are violated, citing source documents",
          "whatYouMayDoNext": ["Step 1 description", "Step 2 description", "Step 3 description"],
          "documentsEvidenceThatMayHelp": ["Evidence Document 1", "Evidence Document 2"],
          "importantLimitations": "clear limitations, state variations, jurisdictional details, and general uncertainties"
        }
        Do not include markdown tags in the output. Return ONLY raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);
      
      return {
        ...parsed,
        sources,
        disclaimer: LEGAL_DISCLAIMER,
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini Rights Error] Falling back to mock analysis:', error.message);
      return { ...mockService.analyzeRights(text), sources };
    }
  },

  // 3. RTI Drafting Agent
  draftRti: async (text) => {
    const sources = retrievalService.search(text, 'rti');
    const sourceText = sources.map(s => `[Source: ${s.title}]\n${s.content || ''}\nSample Qs:\n${s.sample_questions ? s.sample_questions.join('\n') : ''}`).join('\n\n');

    if (!genAI) {
      return { ...mockService.draftRti(text), sources };
    }

    try {
      const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
      const prompt = `
        You are the RTI Drafting Agent of the Civic Action Engine.
        Generate a structured RTI application based on the user request. Ground it on the guidelines below.

        Grounded Source Material:
        ${sourceText || 'Standard RTI Act 2005 guidelines apply.'}

        User Request: "${text}"

        Guidelines:
        - If the applicant name or address is not supplied, use placeholders matching "[Needs your input: Applicant Name]" and "[Needs your input: Applicant Complete Address]". Do not guess or invent them!
        - If the department name or city is not supplied, use placeholders matching "[Needs your input: Public Authority Department Office Name]" and "[Needs your input: City/District]".
        - Structure clear, specific, factual questions. Do not ask for opinions.
        - Generate a formal document layout.

        Respond with a valid JSON object matching this schema:
        {
          "clarificationNeeded": "what missing details should the user supply to make the draft complete?",
          "subject": "formal subject line of the RTI",
          "targetAuthority": "suggested PIO office or department name",
          "rtiDraft": "the full text of the RTI application in a formal, copyable layout",
          "instructions": ["Step 1: pay Rs 10", "Step 2: send by speed post"]
        }
        Do not include markdown tags. Return raw JSON.
      `;

      const result = await model.generateContent(prompt);
      const responseText = result.response.text().trim();
      const parsed = parseStructuredJson(responseText);

      return {
        ...parsed,
        sources,
        disclaimer: "This is a draft RTI application generated under the RTI Act, 2005. It requires your review and verification prior to filing.",
        mode: "LIVE"
      };
    } catch (error) {
      console.error('[Gemini RTI Error] Falling back to mock draft:', error.message);
      return { ...mockService.draftRti(text), sources };
    }
  }
};

module.exports = geminiService;
